import Head from 'next/head'
import Image from 'next/image'
import Profile from '../components/compounds/Profile'
import Song from '../components/compounds/Song'
import ProfileBar from '../components/layouts/ProfileBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <ProfileBar/>



        {/* <Song
        
        SongName = 'Money Longer'
        AlbumName = 'LUV. vs the World'
        SongArtist = 'Lil Uzi Vert'
        SongPreview = 'https://p.scdn.co/mp3-preview/42f7a2733d854fd5bbddb3d62e7df6a78cfac313?cid=774b29d4f13844c495f206cafdad9c86'
        AlbumCover = 'https://images.unsplash.com/photo-1498598457418-36ef20772bb9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'
        /> */}
      </main>

    </div>
  )
}
